### ISSUE TITLE
missing the required client identifier

### ISSUE THREAD

**Issue by QadeerQT** [alchemyguy/YoutubeLaravelApi#9]
I'm gettting **missing the required client identifier** exception while uploading video to youtube
`$authObject  = new AuthenticateService;

		# Replace the identifier with a unqiue identifier for account or channel
		$authUrl = $authObject->getLoginUrl('qadeer.qt@gmail.com','UCC1YGOAVvZBM5d24jRGwSWw');`

**Comment by alchemyguy** [comment]
Did you follow these steps [here](https://github.com/alchemyguy/YoutubeLaravelApi#steps-to-create-your-google-oauth-credentials) and updated the required fields in the `.env` file.
`client_id` is the client identifier, You need to add  ***client_id, client_secret & api_key*** in your `.env` file. 
At least try to follow the documentation instead of creating random issues. It's well-written documentation and tells you everything step by step, you are just jumping into functions.

**Comment by QadeerQT** [comment]
Are you there?

Now, I'm getting **cURL error 6: Could not resolve host: www.googleapis.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)** on youtube-auth routh...

Any idea why this happening?

**Comment by QadeerQT** [comment]
![screenshot from 2019-02-21 23-17-22](https://user-images.githubusercontent.com/39376895/53192043-3ad65a80-362f-11e9-8e59-e60c6df8b53c.png)

**Comment by alchemyguy** [comment]
It means that your system doesn't have curl installed or its is outdated.

**Comment by QadeerQT** [comment]
I have latest Version of Curl

curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets

**Comment by alchemyguy** [comment]
The most recent stable version is 7.64.0, released on 6th of February 2019.

As you can see, It's not a problem with the package, but your system's PHP and CURL installations, I can't help you with that.
